version: '3.8'

services:
  chrome:
    image: browserless/chrome:latest
    container_name: chrome
    ports:
      - "3000:3000"
    networks:
      - test_network

  tests:
    image: tests-image
    container_name: tests
    depends_on:
      - chrome
    environment:
      - BROWSERLESS_URL=http://chrome:3000
    volumes:
      - ./tests:/app/tests #Монтируем тесты в контейнер
      - ./allure-results:/app/allure-results  # Для отчетов
    command: poetry run pytest tests --alluredir=allure-results  # Команда для запуска тестов