name: tests for chrome

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      chrome:
        image: browserless/chrome:latest
        ports:
          - 3000:3000

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Set up Docker Compose
        run: |
          docker-compose -f docker-compose.yml build

      - name: Run tests in Docker
        run: |
          docker-compose up --abort-on-container-exit --build

      - name: Generate Allure Report
        run: |
          docker-compose exec tests poetry run allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Allure Report
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report