name: API Tests with PyTest

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Install Allure CLI
        run: |
          $url = "https://github.com/allure-framework/allure2/releases/download/2.18.1/allure-2.18.1.zip"
          $output = "allure.zip"
          Invoke-WebRequest -Uri $url -OutFile $output
          Expand-Archive -Path $output -DestinationPath allure
          $env:PATH += ";$(pwd)\allure\allure-2.18.1\bin"
          echo "Allure CLI installed successfully."

      - name: Run tests with Allure
        run: poetry run pytest --alluredir=allure-results

      - name: Generate Allure Report
        run: poetry run allure generate allure-results -o allure-report --clean

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          folder: allure-report